admin: add --help option
leil-io/saunafs pull request #14
Opened 2024-02-29 13:42 UTC by uristdwarf

2024-03-04 22:20 UTC, lgsilva3087 requested changes
Please see my comment.

2024-03-04 22:20 UTC, lgsilva3087 commented on src/admin/main.cc
Even if the --help is now accepted. The help output is strange:
![image](https://github.com/leil-io/saunafs/assets/22012909/aeadd03e-6373-4397-ac9d-b6984827f872)
--help should be a valid command and the exception message should not be printed.

2024-03-05 10:34 UTC, uristdwarf commented on src/admin/main.cc
I was working on trying to fix up the option handling and got this error too. I thought just keeping a simple one line change would fix it. Guess not.

I'll try fixing it, but I might just decide to refactor the command-line option handling.

2024-03-05 10:54 UTC, uristdwarf commented on src/admin/main.cc
From my git stash, I tried fixing it but I decided to keep the change simple now.
![image](https://github.com/leil-io/saunafs/assets/7394119/b7780d55-c0ce-4bae-ae57-2a145de43deb)

2024-03-05 14:03 UTC, lgsilva3087 approved these changes
Ready.

2024-03-05 14:03 UTC, lgsilva3087 commented on src/admin/main.cc
I understand, please create the tasks to fix it later.

2024-03-05 16:34 UTC, merged