Feature metadata handling
leil-io/saunafs pull request #15
Opened 2024-02-29 23:07 UTC by Antuan-AE

To speed up the master metadata loading process, all metadata sections are loaded in parallel. 
Support for metadata versions before v2.9 is deprecated. 
Metadata File with v2.9 splits its content into sections which allows it to be handled in parallel. 
The Metadata file signature is changed.
New algorithm is fully tested with two added functional tests to SanityChecks.

This change breaks compatibility with previous version because of Metadata file header signature.

2024-03-04 21:50 UTC, lgsilva3087 requested changes
Almost ready. Please see my suggestions.

2024-03-04 23:51 UTC, Antuan-AE commented on src/master/metadata_loader.cc
> +#include "common/platform.h"
done

2024-03-04 23:51 UTC, Antuan-AE commented on src/master/filesystem_store.cc
> +	int8_t s;
done

2024-03-04 23:52 UTC, Antuan-AE commented on src/master/filesystem_store.cc
> +static constexpr int8_t kOpFailure = -1;
done

2024-03-04 23:53 UTC, Antuan-AE commented on src/master/filesystem_store.cc
>  constexpr uint8_t kMetadataVersionSaunaFS = 0x16;
This is part of the dumping algorithm. Will be remove after the new dumping algorithm implementation is finished.

2024-03-04 23:53 UTC, Antuan-AE commented on src/master/filesystem_store.cc
> +#include "master/filesystem_store.h"
done

2024-03-04 23:53 UTC, Antuan-AE commented on src/master/filesystem.h
> +						 uint32_t *links, uint32_t *chunks, uint64_t *length, uint64_t *size, uint64_t *rsize);
done

2024-03-04 23:53 UTC, Antuan-AE commented on src/master/chunks.cc
> +//#include "common/memory_file.h"
done

2024-03-04 23:54 UTC, Antuan-AE commented on src/common/parallel_helpers.h
removed

2024-03-04 23:54 UTC, Antuan-AE commented on src/common/parallel_helpers.cc
removed

2024-03-05 11:32 UTC, Antuan-AE commented on src/master/chunks.cc
> +#include "master/filesystem_store.h"
done

2024-03-05 11:33 UTC, Antuan-AE commented on src/master/chunks.h
> +#include "master/filesystem_store.h"
done

2024-03-05 11:40 UTC, Antuan-AE commented on src/master/filesystem_store.cc
> +#include "master/filesystem_freenode.h"
done

2024-03-05 22:19 UTC, ralcolea reviewed
PR is almost complete. Please see my suggestions.

I also noticed that some commit messages have minor typos. Consider reviewing the following commits messages before merging the branch:

  * a4c2f1c
  * 3999491
  * 9c6e55e
  * b6a2592
  * e778de2
  * c971826 
  * df44a9b

2024-03-06 00:15 UTC, Antuan-AE commented on src/master/metadata_loader.cc
> +*/#include "common/platform.h"
done

2024-03-06 00:18 UTC, Antuan-AE commented on src/master/metadata_loader.cc
> +	 SaunaFS is free software: you can redistribute it and/or modify
done

2024-03-06 00:20 UTC, Antuan-AE commented on src/master/locks.cc
> +#include "master/locks.h"
removed

2024-03-06 00:23 UTC, Antuan-AE commented on src/master/filesystem_store_acl.cc
> +        try {
done

2024-03-06 00:27 UTC, Antuan-AE commented on src/master/filesystem_store_acl.cc
> +		s = fs_load_posix_acl(options.metadataFile, options.offset, options.ignoreFlag, true);
done

2024-03-06 00:28 UTC, Antuan-AE commented on src/master/filesystem_store_acl.cc
> +		s = fs_load_posix_acl(options.metadataFile, options.offset, options.ignoreFlag, false);
done

2024-03-06 00:30 UTC, Antuan-AE commented on src/master/filesystem_store_acl.cc
> +		s = fs_load_legacy_acl(options.metadataFile, options.offset, options.ignoreFlag);
done

2024-03-06 00:35 UTC, Antuan-AE commented on src/master/filesystem_store_acl.cc
> +        uint32_t sizeofsize = sizeof(size);
done

2024-03-06 16:32 UTC, ralcolea approved these changes
I think all the suggestions were addressed. However, I still notice two typos, probably missed. I list them below:
  * 3eb26f9: master: Add counter to trach amount of link nodes
     - Replace trach by track in the commit title.

  * bb068fb: master: Use callbacks to handle metadata loading
     - Not all the sentences have final point.
     - I think there is a typo in the last sentence, Allign -> Align (or something else).
  
My last suggestion is to consider squashing commits for applying code review suggestions. It will help reducing the number of commits in the PR.

2024-03-06 23:58 UTC, lgsilva3087 approved these changes
Please fix the typos requested by Crash before merging.

2024-03-07 14:54 UTC, merged