chunkserver: Reallocate methods for plugin reuse
leil-io/saunafs pull request #19
Opened 2024-03-06 19:04 UTC by rolysr

Relocate disk space utilities to chunkserver-common for plugins access.
The main reason for doing this was to enable some important methods from hddspacemgr.cc
to be accessed from new plugins implemented.

- Move methods from `hddspacemgr.cc` to `hdd_utils.cc` for plugin-compatible access.
- Adjust `hddspacemgr.cc` to use the new `hdd_utils.cc` location, ensuring plugin compatibility.
- Prepare `hdd_utils.cc` for plugin support by enhancing modularity and accessibility.

The reallocated methods were:
- `chunkWriteCrc`
- `hddIOEnd`
- `hddIOBegin`
- `hddScansInProgress`
- `hddChunkFindAndLock`
- `hddChunkFindOrCreatePlusLock`
- `hddRecreateChunk`
- `hddDeleteChunkFromRegistry`

Also, deleted code related to defragmentation on `hddTesterThread` from `hddspacemgr.cc`

2024-03-06 23:34 UTC, lgsilva3087 requested changes
Please see my comments.
Also, please improve the commit message to explain why we need to do it and add the co-authors, something like this:

```
chunkserver: Make symbols visible in plugins

Some symbols needed for the defragmentation were not visible from the
plugins. This commit moves them to the chunkserver-common library.

The flag CMAKE_ENABLE_EXPORTS was added to share the same symbol
references between the chunkserver and the plugins. This is needed
because the plugins are shared libraries. If this variable is not set
or OFF, then the same global, probably static, variable will be
different on each executable (chunkserver and plugin).

The call to the defragmentation was removed from the tester thread, it
is now responsibility of the concrete plugin.

Co-authored-by: Crash <crash@leil.io>
Co-authored-by: guillex <guillex@leil.io>
```

2024-03-06 23:34 UTC, lgsilva3087 commented on CMakeLists.txt
> +set(CMAKE_ENABLE_EXPORTS ON)
Please consider this change:
```
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Enable symbol export for loadable modules, ensuring same shared resource
# references. Needed for the plugins, as they are shared libraries.
set(CMAKE_ENABLE_EXPORTS ON)
```
IMHO, it explains better why we are introducing this flag. It is also separated from the C++ standard definition.

2024-03-06 23:34 UTC, lgsilva3087 commented on src/chunkserver/chunkserver-common/global_shared_resources.h
> +#include "devtools/request_log.h"
This include should not be here. It is needed instead in hdd_utils.cc.

2024-03-06 23:34 UTC, lgsilva3087 commented on src/chunkserver/chunkserver-common/hdd_utils.h
> +#include "common/event_loop.h"
Not needed here. Please move it to the .cc file.
Also, please add the common/platform.h to both files (.h and .cc) at the beginning.

2024-03-06 23:34 UTC, lgsilva3087 commented on src/chunkserver/hddspacemgr.cc
> +
common/platform.h is repeated.
common/saunafs_error_codes.h must be in the proper group (below).

2024-03-06 23:34 UTC, lgsilva3087 commented on src/chunkserver/hddspacemgr.h
> +#include "chunkserver-common/hdd_utils.h"
Should be in the .cc file, you are not using it here.

2024-03-07 18:09 UTC, Antuan-AE commented on src/chunkserver/chunkserver-common/hdd_utils.cc
> +			// FIXME(hazeman): We are probably leaking fd here.
Its this old comment still applicable to the new implementation? Please review it and remove the comment if appropriate.

2024-03-07 18:15 UTC, Antuan-AE commented on src/chunkserver/chunkserver-common/hdd_utils.cc
> +			// FIXME(hazeman): We are probably leaking fd here.
Maybe is best to do it in other PR.

2024-03-07 18:16 UTC, Antuan-AE approved these changes
LGTM

2024-03-07 20:07 UTC, lgsilva3087 approved these changes

2024-03-11 20:36 UTC, ralcolea approved these changes
I did some minor suggestions, but are not stoppers for merging this branch.
Nice job!! :+1:

2024-03-11 20:36 UTC, ralcolea commented on src/chunkserver/chunkserver-common/hdd_utils.cc
> +		    chunk->owner() != nullptr) {
Consider comparing `chunk->owner()` with `DiskNotFound` instead of `nullptr`. 
This is only a suggestion because is out of the scope of this PR.

2024-03-12 13:04 UTC, uristdwarf commented
@rolysr Have you pushed your resolved conversation changes up? I would like to merge it.

2024-03-12 15:44 UTC, merged